### ISSUE TITLE
Adicionar nome do jogador na interface gráfica

### ISSUE THREAD

**Issue by janynnegomes** [pedroluzio/EducationEllie#11]
Em todas as janelas, é interessante identificar o nome do jogador, que atualmente está salvo na base de dados SQLite.

**Comment by pedroluzio** [comment]
Feito, ficou só a faltar o jogo das cores, acho que puderá ficar ara quando esse jogo estiver completamente concluído.

**Comment by janynnegomes** [comment]
Vou testar localmente e fazer o merge para o master, com essas alterações.

**Comment by pedroluzio** [comment]
Feito nos três jogos e feito o merge com o master
